Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > Fails presubmit with:
> > 
> > java.lang.AssertionError: Kernel's ABI has changed. See go/kernel-abi-monitoring for details.
> >  expected:<SUCCESS> but was:<FAILED>
> > 	at org.junit.Assert.fail(Assert.java:88)
> > 	at org.junit.Assert.failNotEquals(Assert.java:834)
> > 	at org.junit.Assert.assertEquals(Assert.java:118)
> > 
> > Presubmit failure looks unrelated and the test has been failing recently
> > https://blackbox.googleplex.com/search/details?namespace=android&branch=aosp_kernel-common-android-4.19&target=kernel_aarch64&atpConfig=apct%2Fbuild%2Fkernel_image_check&testTag=stub&package=com.android.build.tests&class=com.android.build.tests.KernelImageCheck&testSuite=stub&testCase=com.android.build.tests.KernelImageCheck%23test_stable_abi&type=functional
> > 
> > Sandeep, any insight into why the abi check is failing?
> 
> The actual failure is on the dma_buf struct changing:
> 
> 'struct dma_buf at dma-buf.h:282:1' changed:
>   type size changed from 1984 to 1920 (in bits)
>   1 data member deletion:
>     'const char* dma_buf::name', at offset 768 (in bits) at dma-buf.h:291:1
> 
> 
> However, that attribute was added with this CL:
>   https://android-review.googlesource.com/c/kernel/common/+/984048

This was my changes from yesterday. I took care of updating the ABI and added this CL to the same topic. Should go through OK now.

Patch-set: 2
Reviewer: Gerrit User 1293738 <1293738@85c56323-6fa9-3386-8a01-6480fb634889>