build_utils: Update the default system_dlkm props
* Add some missing ext4 properties.
* Add the selinux_fc option to ensure all files on the system_dlkm image
  have a proper selinux label.
* Update the fs_type to fix this error:

  ---8<---
    File "build_image.py", line 940, in main
    File "build_image.py", line 619, in BuildImage
    File "build_image.py", line 428, in BuildImageMkfs
  __main__.BuildImageError: Error: unknown filesystem type:
  ---8<---

Tests: verify GKI modules load with GKI boot and system_dlkm images
Bug: 282917063
Change-Id: I73e1b3d9bfca8c5e66e68a54d27a8cfe55670d4a