build.sh: Disable KMI_SYMBOL_LIST_STRICT_MODE when using LTO=none
When building with LTO=none, the build will usually fail
due to symbol issues such as:

ERROR: Differences between ksymtab and symbol list detected!
Symbols missing from ksymtab:
 - __cfi_slowpath_diag
 - __ubsan_handle_cfi_check_fail_abort

This change disables KMI_SYMBOL_LIST_STRICT_MODE for LTO=none
builds, so that the build will succeed.

Because we don't want developers submitting patches that create
KMI symbol issues, this patch also adds a warning at the end of
the build to ensure developers test with LTO=thin or LTO=full
before submitting.

Suggested-by: Peter Collingbourne <pcc@google.com>
Signed-off-by: John Stultz <jstultz@google.com
Change-Id: Ifef76fdc4aa574afd4c080672455f4c7620715d4