download_from_ci: Fix download dir clean up
git rm -rf doesn't remove the directory causing a traceback
stating the directory exists.

File "/usr/local/google/home/ramjiyani/repos/android14-5.15/build/kernel/gki/download_from_ci", line 345, in clean_download_dir
    os.mkdir(download_dir)
FileExistsError: [Errno 17] File exists: '/usr/local/google/home/ramjiyani/repos/aosp/kernel/prebuilts/5.15/arm64'

Replace os.mkdir() call with os.mkdirs() call with exist_ok=True

Fixes: fbc9d84513d6 ("download_from_ci: add 16k experiment")
Bug: 232431151
Test: TH
Change-Id: I86219678c50e2483e1d5ca0d7616865601f0424a
Signed-off-by: Ramji Jiyani <ramjiyani@google.com>